services:
  db:
    image: postgres:16
    network_mode: host
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGPORT: 5432
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    network_mode: host
    depends_on:
      - db
    environment:
      HOST: 127.0.0.1
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./:/mnt/extra-addons/versioning_app
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_web_data:
