version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:19.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./versioning_app:/mnt/extra-addons/versioning_app
    restart: unless-stopped

volumes:
  odoo_db_data:
  odoo_web_data:
